on:
  pull_request:
    types: [opened, synchronize]
jobs:
  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Flake8 Linter Step
        uses: betrybe/flake8-linter-action@v1.0
        id: flake8_linter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.number }}
      - name: Pytest Evaluator Step
        uses: betrybe/pytest-evaluator-action@v1.1
        with:
          repository-main-branch: master
          repository-test-name: 'betrybe/sd-0x-project-exploring-the-protocols-tests'
          repository-test-branch: 'main'
        id: pytest_evaluator
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.pytest_evaluator.outputs.result }}
          environment: staging
          pr-number: ${{ github.event.number }}
